  ---
  - name: Push the message about deploy to kafka queue
    command: "echo -e "{{ landscape_name }}|{{ deploy_artifact_name }} | {{ kafka_home }}bin/kafka-console-producer.sh --broker-list {{ kafka_host }}:{{ kafka_port }} --topic {{ topic_name }}"
