---
- name: Produces messages jenkins regarding queued builds ready for deployment
  hosts: kafkaclient
  gather_facts: False

  # load AWS variables from this group vars file
  vars_files:
  - group_vars/all

  roles:
  - consume
